name: lumitales

services:
  liv-book-reader:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - lumitales-books:/app/books
      - lumitales-data:/app/data

volumes:
  lumitales-books:
    name: lumitales-books
  lumitales-data:
    name: lumitales-data
